apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  template:
    metadata:
      name: first-pod
      labels:
        app: myapp
        company: xyz
    spec:
      containers:
        - name: first-pod
          image: nginx